default = "auto"
default_english = "qwen"
default_tagged = "chroma-aio"
#default_edit = "nanobanana"

[aliases]
qwen = "qwen_image_fp8"
fanart = "hassaku"
fanart-cute = "monody"
pasanctuary = "pasanctuary-5.0"
dream = "qwen_image_fp8"
animavivid = "animavividxl"

[templates.sdxl]
name = "sdxl"
description = "Default SDXL settings"
tags = ["booru", "english"]

[templates.sdxl.backend.ComfyUI]
cfg = 4.5
sampler = "er_sde"
scheduler = "sgm_uniform"
steps = 28
resolution = [1024, 1024]
two_stage = true
upscale_factor = 1.5
stage2_denoise = 0.5
stage2_sampler = "euler"
stage2_scheduler = "beta"

[templates.illustrious]
inherit = "sdxl"
description = "Illustrious-based settings"
tags = ["booru", "fanart"]
[templates.illustrious.prompt_defaults]
negative_append = "bored, 3d, bad quality, worst quality, lowres, jpeg artifacts, bad anatomy, bad hands, multiple views, signature, watermark, censored, ugly, messy"

[templates.noobai]
inherit = "sdxl"
tags = ["booru", "fanart"]
[templates.noobai.backend.ComfyUI]
cfg = 4.5
sampler = "er_sde"
scheduler = "sgm_uniform"
steps = 28
resolutions = [
    "768x1344",
    "832x1216",
    "896x1152",
    "1024x1024",
    "1024x1536",
    "1152x896",
    "1216x832",
    "1344x768",
    "1536x1024",
]
two_stage = false

[templates.flux]
tags = ["english", "booru"]
[templates.flux.backend.ComfyUI]
vae = "ae.safetensors"
clip = "t5xxl_fp16.safetensors"

[models.oneobsession]
name = "oneobsession"
inherit = "noobai"
tags = ["booru", "fanart"]
backend.ComfyUI.checkpoint = "xl-noob/oneObsession_v16Noobai.safetensors"

[models.qwen_image_fp8]
name = "qwen_image_fp8"
description = "Qwen-Image. A general-purpose model; use English, preferably."
tags = ["english", "booru", "recommended"]
[models.qwen_image_fp8.backend.ComfyUI]
unet = "qwen/qwen_image_fp8_e4m3fn.safetensors"
clip = "qwen_2.5_vl_7b_fp8_scaled.safetensors"
vae = "qwen_image_vae.safetensors"
cfg = 3.5
sampler = "euler_ancestral"
scheduler = "beta"
steps = 20
resolution = [1280, 1280]

[models.walnut]
name = "walnut"
inherit = "illustrious"
description = "PlantMilkTeaWalnut. A fanart model; use tags!"
tags = ["fanart", "booru", "recommended"]

[models.walnut.backend]
ComfyUI.checkpoint = "xl-ill/plantMilkModelSuite_walnut.safetensors"

[models.chroma-aio]
name = "chroma-aio"
description = "chroma-Anime-AIO. Use anime tags and English."
tags = ["english", "booru", "recommended"]
[models.chroma-aio.prompt_defaults]
positive_prepend = "Modern 2020s anime."
[models.chroma-aio.backend.ComfyUI]
checkpoint = "chroma/Chroma-Anime-AIO.safetensors"
cfg = 4.0
sampler = "euler_ancestral"
scheduler = "sgm_uniform"
steps = 24
resolution = [1280, 1280]

# Autogenerated models below this line.
# Do not edit, unless to un-autogenerate them.

[models.chroma]
name = "chroma"
inherit = "flux"
description = "Chroma. Use anime tags and English."
tags = ["english", "booru", "recommended"]

[models.chroma.prompt_defaults]
positive_prepend = "The scene is rendered in a modern 2020s anime style with bold, clean linework and careful shading."
negative_prepend = "low quality, ugly, unfinished, out of focus, deformed, disfigure, blurry, smudged, restricted palette, flat colors"

[models.chroma.backend.ComfyUI]
unet = "chroma/Chroma1-HD.safetensors"
clip = "chroma/t5xxl_fp16.safetensors"
cfg = 4.0
sampler = "euler_ancestral"
scheduler = "sgm_uniform"
steps = 40
resolution = [1024, 1024]

[models.hassaku]
name = "hassaku"
inherit = "illustrious"
description = "A multi-style fanart model. Less glitchy than Quillworks."
tags = ["booru", "fanart", "recommended"]
[models.hassaku.prompt_defaults]
negative_prepend = "bored, worst quality, bad quality"
[models.hassaku.backend.ComfyUI]
checkpoint = "xl-ill/hassakuXLIllustrious_v30.safetensors"
cfg = 5.5

[models.ntrmix]
name = "ntrmix"
inherit = "illustrious"
description = "NTRMix XIII. Illustrious-based; for fanart. Use tags."

[models.ntrmix.prompt_defaults]
positive_append = "masterpiece, best quality, amazing quality, very aesthetic, absurdres, newest, volumetric lighting"
negative_append = "shiny skin, bored, simple background, worst quality, old, early, low quality, lowres, bad hands, mutated hands, censored, monochrome"

[models.ntrmix.backend]
ComfyUI.checkpoint = "xl-ill/ntrMIXIllustriousXL_xiii.safetensors"

[models."ntrmix-40"]
name = "ntrmix-40"
inherit = "illustrious"
description = "NTRMix v4.0. Illustrious-based; for fanart. Use tags."

[models."ntrmix-40".prompt_defaults]
positive_append = "masterpiece, best quality, newest, absurdres, highres"
negative_append = "bored, simple background, worst quality, old, early, low quality, lowres, bad hands, mutated hands, censored, monochrome"

[models."ntrmix-40".backend]
ComfyUI.checkpoint = "xl-ill/ntrMIXIllustriousXL_v40.safetensors"

[models.monody]
name = "monody"
inherit = "illustrious"
description = "Monody Illustrious. For cute fanart. Use tags."

[models.monody.prompt_defaults]
positive_append = "masterpiece (quality), best quality, good quality, newest"
negative_append = "bored, greyscale, simple background, worst quality, bad quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, multiple views, signature, watermark, censored, greyscale, monochrome"

[models.monody.backend]
ComfyUI.checkpoint = "xl-ill/monodyIllustrious_a1.safetensors"

[models."pasanctuary-1.0"]
name = "pasanctuary-1.0"
inherit = "illustrious"
description = "PASanctuary SDXL 1.0. For fanart. Use tags."

[models."pasanctuary-1.0".prompt_defaults]
positive_append = "masterpiece, best quality, good quality, newest, absurdres, highres"
negative_append = "worst quality, old, early, low quality, lowres, bad hands, mutated hands, greyscale, (nsfw, see-through:0.7)"

[models."pasanctuary-1.0".backend]
ComfyUI.checkpoint = "xl-ill/pasanctuarySDXL_v10.safetensors"

[models."pasanctuary-2.0"]
name = "pasanctuary-2.0"
inherit = "illustrious"
description = "PASanctuary SDXL 2.0. For fanart. Use tags."

[models."pasanctuary-2.0".prompt_defaults]
positive_append = "masterpiece, best quality"
negative_append = "worst quality, old, early, low quality, lowres, bad hands, mutated hands, greyscale, (nsfw, see-through:0.7)"

[models."pasanctuary-2.0".backend]
ComfyUI.checkpoint = "xl-ill/pasanctuarySDXL_v20.safetensors"

[models."pasanctuary-3.0"]
name = "pasanctuary-3.0"
inherit = "illustrious"
description = "PASanctuary SDXL 3.0. For fanart. Use tags."

[models."pasanctuary-3.0".prompt_defaults]
positive_append = "masterpiece, best quality, good quality, newest, absurdres, highres"
negative_append = "worst quality, old, early, low quality, lowres, bad hands, mutated hands, greyscale, (nsfw, see-through:0.7)"

[models."pasanctuary-3.0".backend]
ComfyUI.checkpoint = "xl-ill/pasanctuarySDXL_v30.safetensors"

[models."pasanctuary-4.0"]
name = "pasanctuary-4.0"
inherit = "illustrious"
description = "PASanctuary SDXL 4.0. For fanart. Use tags."

[models."pasanctuary-4.0".prompt_defaults]
positive_append = "masterpiece, best quality, good quality, newest, absurdres, highres"
negative_append = "worst quality, old, early, low quality, lowres, bad hands, mutated hands, greyscale, (nsfw, see-through:0.7)"

[models."pasanctuary-4.0".backend]
ComfyUI.checkpoint = "xl-ill/pasanctuarySDXL_v40.safetensors"

[models."pasanctuary-5.0"]
name = "pasanctuary-5.0"
inherit = "illustrious"
description = "PASanctuary SDXL 5.0. For fanart. Use tags."

[models."pasanctuary-5.0".prompt_defaults]
positive_append = "masterpiece, best quality, newest, absurdres, highres"
negative_append = "worst quality, old, early, low quality, lowres, bad hands, mutated hands, greyscale, (nsfw, see-through:0.7)"

[models."pasanctuary-5.0".backend]
ComfyUI.checkpoint = "xl-ill/pasanctuarySDXL_v50.safetensors"

[models.illustriousxl]
name = "illustriousxl"
inherit = "illustrious"
description = "Illustrious 1.0. For fanart. Use tags and English."

[models.illustriousxl.prompt_defaults]
negative_append = "3d, bored, simple background, worst quality, old, early, low quality, lowres, bad hands, mutated hands, censored, monochrome"

[models.illustriousxl.backend.ComfyUI]
checkpoint = "xl-ill/Illustrious-XL-v1.0.safetensors"

[models.rouwei]
name = "rouwei"
inherit = "sdxl"
description = "Rouwei, an opinionated fanart model. Use tags."
tags = ["booru"]

[models.rouwei.prompt_defaults]
positive_append = "newest, best quality, rouwei"
negative_append = "worst quality, low quality, watermark"

[models.rouwei.backend.ComfyUI]
checkpoint = "xl-ill/rouwei_061Vpred.safetensors"

[models.quillworks]
name = "quillworks"
inherit = "sdxl"
description = "A multi-style fanart model. Try Ink Sketch Style, BrushWork, Anime, Cartoon, 3d cartoon, sketch, watercolor, realistic or digital art style"
tags = ["booru", "fanart"]

[models.quillworks.backend.ComfyUI]
checkpoint = "xl-ill/QuillworksIllustrious_QuillworksV15.safetensors"

[models.animaginexl]
name = "animaginexl"
inherit = "sdxl"
description = "AniMagine XL. Use tags, NovelAI style."

[models.animaginexl.backend.ComfyUI]
checkpoint = "xl/animagineXLV3_v30.safetensors"

[models.animavividxl]
name = "animavividxl"
inherit = "sdxl"
description = "AniMaVivid XL. Use tags."
[models.animavividxl.prompt_defaults]
negative_append = "(worst quality, low quality:1.6)"
[models.animavividxl.backend.ComfyUI]
checkpoint = "xl/animavivid_v10.safetensors"
sampler = "euler_ancestral"
scheduler = "karras"
stage2_sampler = "euler_ancestral"
stage2_scheduler = "karras"

[models.nanobanana]
name = "nanobanana"
description = "NanoBanana, aka. Gemini-2.5-flash-image-preview"
backend = "NanoBanana"
tags = ["english"]
