default = "fanart"

[aliases]
"fanart" = "walnut"

[templates.illustrious]
name = "illustrious"
description = "Template for Illustrious-based models"
[templates.illustrious.prompt_defaults]
negative_append = "bored, 3d, bad quality, worst quality, lowres, jpeg artifacts, bad anatomy, bad hands, multiple views, signature, watermark, censored, ugly, messy"
[templates.illustrious.backend]
StableDiffusion = { cfg = 4.5, sampler = "er_sde", scheduler = "beta", steps = 25, resolution = [
    1024,
    1024,
] }

[models.walnut]
name = "walnut"
inherit = "illustrious"
description = "PlantMilkTeaWalnut. A fanart model; use tags!"

[models.walnut.backend]
StableDiffusion = { checkpoint = "xl-ill/plantMilkModelSuite_walnut.safetensors" }

[models.nanobanana]
name = "nanobanana"
description = "NanoBanana, aka. Gemini-2.5-flash-image-preview"
backend = "NanoBanana"
